version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - electric

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

  electric:
    image: electricsql/electric-next
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres


volumes:
  postgres-data: {}
  caddy_data: {}
  caddy_config: {}

networks:
  default:
    name: app-network